name: Full Build

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Full build
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.5
      with:
        java-version: 17
    - id: pull-images
      name: Pull Docker images
      run: |
        docker pull gvenzl/oracle-xe:18-slim
        docker pull mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04

# LINT CODE
    - id: read-env
      name: Use super-linter environmental variables
      shell: bash
      run: |
        # Use super-linter environmental variables
        cat .github/super-linter.env >> "$GITHUB_ENV"
    - id: lint-code-base
      name: Lint Code Base
      uses: github/super-linter/slim@v5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main


# BUILD AND TEST
    - id: build-test
      name: Build all modules and run tests
      run: |
        mvn \
          -X \
          -DtrimStackTrace=false \
          --no-transfer-progress \
          --batch-mode \
          -Dheavydb \
          test
