name: Full Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Full build
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.3
    - id: pull-images
      name: Pull Docker images
      run: |
        docker pull gvenzl/oracle-xe:18-slim
        docker pull mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04

# LINT CODE
    - id: lint-code-base
      name: Lint Code Base
      uses: docker://github/super-linter:v2.2.2
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_XML: true
        VALIDATE_MD: true
        VALIDATE_BASH: true
        VALIDATE_PYTHON: false
        VALIDATE_RUBY: false
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_DOCKER: true
        VALIDATE_CSS: true
        VALIDATE_ENV: true

# BUILD AND TEST
    - id: build-test
      name: Build all modules and run tests
      run: |
        mvn \
          -X \
          -DtrimStackTrace=false \
          --no-transfer-progress \
          --batch-mode \
          -Dheavydb \
          test
