name: Quick Build

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Quick build
    runs-on: ubuntu-latest

    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.3.5
      with:
        java-version: 17

# BUILD AND TEST
    - id: build-test
      name: Build and run tests
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          package

# UPLOAD SQLite DATABASE
    - id: upload-sqlite
      name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chinook-sqlite
        path: target/chinook-database-2.2.1.sqlite


  diagram:
    name: Generate diagram
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    permissions:
      # Give the default GITHUB_TOKEN write permission
      # to commit and push the added or changed files
      # to the repository.
      contents: write

    steps:

# DOWNLOAD SQLite DATABASE
    - id: download-sqlite
      name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: chinook-sqlite
    - id: list-files
      name: List All Files
      run: |
        # List all files in the current directory
        ls -al

# GENERATE SchemaCrawler DIAGRAM
    - id: schemacrawler
      name: Run SchemaCrawler Action with specified command-line
      uses: schemacrawler/SchemaCrawler-Action@v16.21.1
      with:
        entrypoint: /opt/schemacrawler/bin/schemacrawler.sh
        args: --server=sqlite --database=target/chinook-database-2.2.1.sqlite --title "Chinook Database, v2.2.1" --info-level=standard --command=schema --output-file chinook_schema_diagram.png --log-level=CONFIG

    - id: check-success
      name: Fail the entire job if SchemaCrawler run failed
      shell: bash
      run: |
        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] && echo "SchemaCrawler run succeeded" || echo "SchemaCrawler run failed"
        [ ${{ env.SC_EXIT_STATUS }} -eq 0 ] || exit 1

    - id: push-generated-graph
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update database schema diagram from CI build"
        branch: main
        commit_options: '--no-verify --no-signoff'
        commit_user_name: "Sualeh Fatehi"
        commit_user_email: "sualeh@hotmail.com"
        commit_author: "Sualeh Fatehi <sualeh@hotmail.com>"
